### ISSUE TITLE
Check interrupt capabilities for 2nd MCP interrupt port

### ISSUE THREAD

**Issue by adrianstevens** [WildernessLabs/Meadow.ProjectLab#12]
D10 doesn't support interrupts on Feather V1 ..... check capabilities and skip interrupt ports to unlock RS-485 and Mikrobus functionality for Meadow V1 boards connected to Proj Lab v2

https://github.com/WildernessLabs/Meadow.ProjectLab/blob/develop/Source/Meadow.ProjectLab/ProjectLab.cs#L87

**Comment by bryancostanich** [comment]
@adrianstevens this is for the old Project Lab yeah?

**Comment by adrianstevens** [comment]
@bryancostanich yeah old Project Lab so I vote we close
